
  0%|                                                                                                                              | 0/3000 [00:00<?, ?it/s]
An arbitrary loader is used instead of Validation loader
Traceback (most recent call last):
  File "/home/clay/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
TypeError: argsort() received an invalid combination of arguments - got (order=NoneType, kind=NoneType, axis=int, ), but expected one of:
 * (int dim, bool descending)
 * (name dim, bool descending)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "emb_train.py", line 160, in <module>
    trainer.train_by_num_epoch(args.num_epochs)
  File "/home/clay/userdata/title_generation/emb_trainer.py", line 93, in train_by_num_epoch
    train_loss, train_acc = self.validate(external_loader=self.train_loader)
  File "/home/clay/userdata/title_generation/emb_trainer.py", line 454, in validate
    sorted_euc_idx = np.argsort(euc_sim, axis=-1)
  File "<__array_function__ internals>", line 180, in argsort
  File "/home/clay/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1120, in argsort
    return _wrapfunc(a, 'argsort', axis=axis, kind=kind, order=order)
  File "/home/clay/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/clay/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/home/clay/.local/lib/python3.8/site-packages/torch/_tensor.py", line 757, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.